#ChipScope Core Inserter Project File Version 3.0
#Fri Jul 21 11:38:44 EDT 2017
Project.device.designInputFile=D\:\\MBImager\\OK_imager1\\OK_imager_cs.ngc
Project.device.designOutputFile=D\:\\MBImager\\OK_imager1\\OK_imager_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\MBImager\\OK_imager1\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=fsmind0
Project.filter<11>=fsmind1
Project.filter<12>=rst
Project.filter<13>=flag_2frames
Project.filter<14>=flag2frames
Project.filter<15>=FSMstop
Project.filter<16>=fsm_stat_i
Project.filter<17>=fsm_stat
Project.filter<18>=ROImager_inst/fsm_stat_
Project.filter<1>=stream
Project.filter<2>=CLK_HS
Project.filter<3>=trigger_proj
Project.filter<4>=flag_2grame
Project.filter<5>=flag_1frame
Project.filter<6>=roimager_inst/stream
Project.filter<7>=roimager_inst
Project.filter<8>=roimager_inst/fsmind1
Project.filter<9>=roimager_inst/fsmind0
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=CLK_HS
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=FIFO_Patterns_cam rd_en
Project.unit<0>.dataChannel<10>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<0>
Project.unit<0>.dataChannel<1>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<9>
Project.unit<0>.dataChannel<2>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<8>
Project.unit<0>.dataChannel<3>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<7>
Project.unit<0>.dataChannel<4>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<6>
Project.unit<0>.dataChannel<5>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<5>
Project.unit<0>.dataChannel<6>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<4>
Project.unit<0>.dataChannel<7>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<3>
Project.unit<0>.dataChannel<8>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<2>
Project.unit<0>.dataChannel<9>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<1>
Project.unit<0>.dataDepth=16384
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=11
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=FIFO_Patterns_cam rd_en
Project.unit<0>.triggerChannel<1><0>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<9>
Project.unit<0>.triggerChannel<1><1>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<8>
Project.unit<0>.triggerChannel<1><2>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<7>
Project.unit<0>.triggerChannel<1><3>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<6>
Project.unit<0>.triggerChannel<1><4>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<5>
Project.unit<0>.triggerChannel<1><5>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<4>
Project.unit<0>.triggerChannel<1><6>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<3>
Project.unit<0>.triggerChannel<1><7>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<2>
Project.unit<0>.triggerChannel<1><8>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<1>
Project.unit<0>.triggerChannel<1><9>=FIFO_Patterns_cam U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<0>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerPortCount=2
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerPortWidth<1>=10
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
