#ChipScope Core Inserter Project File Version 3.0
#Mon Jun 26 18:35:45 EDT 2017
Project.device.designInputFile=D\:\\MBImager\\OK_imager1\\OK_imager_cs.ngc
Project.device.designOutputFile=D\:\\MBImager\\OK_imager1\\OK_imager_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\MBImager\\OK_imager1\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=flag_2frames
Project.filter<11>=flag2frames
Project.filter<12>=FSMstop
Project.filter<13>=fsm_stat_i
Project.filter<14>=fsm_stat
Project.filter<15>=ROImager_inst/fsm_stat_
Project.filter<16>=ROImager_inst/fsm_stat_i<0>
Project.filter<17>=ROImager_inst/fsm_stat_i<5>
Project.filter<18>=ROImager_inst/fsm_stat<5>
Project.filter<1>=flag_2grame
Project.filter<2>=flag_1frame
Project.filter<3>=roimager_inst/stream
Project.filter<4>=roimager_inst
Project.filter<5>=roimager_inst/fsmind1
Project.filter<6>=roimager_inst/fsmind0
Project.filter<7>=fsmind0
Project.filter<8>=fsmind1
Project.filter<9>=rst
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=fifo_mem_pats wr_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=fifo_mem_pats wr_en
Project.unit<0>.dataChannel<10>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<6>
Project.unit<0>.dataChannel<11>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<5>
Project.unit<0>.dataChannel<12>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<4>
Project.unit<0>.dataChannel<13>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<3>
Project.unit<0>.dataChannel<14>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<2>
Project.unit<0>.dataChannel<15>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<1>
Project.unit<0>.dataChannel<16>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<0>
Project.unit<0>.dataChannel<17>=fifo_mem_pats rd_en
Project.unit<0>.dataChannel<18>=ROImager_inst/fsm_stat_i<6>
Project.unit<0>.dataChannel<19>=ROImager_inst/fsm_stat_i<5>
Project.unit<0>.dataChannel<1>=fifo_mem_pats din<7>
Project.unit<0>.dataChannel<20>=ROImager_inst/fsm_stat_i<4>
Project.unit<0>.dataChannel<21>=ROImager_inst/fsm_stat_i<3>
Project.unit<0>.dataChannel<22>=ROImager_inst/fsm_stat_i<2>
Project.unit<0>.dataChannel<23>=ROImager_inst/fsm_stat_i<1>
Project.unit<0>.dataChannel<24>=flag_2frames
Project.unit<0>.dataChannel<25>=wire10 ep_dataout<0>
Project.unit<0>.dataChannel<26>=ROImager_inst/FSMIND1_i
Project.unit<0>.dataChannel<27>=ROImager_inst/FSMIND0ACK_i
Project.unit<0>.dataChannel<2>=fifo_mem_pats din<6>
Project.unit<0>.dataChannel<3>=fifo_mem_pats din<5>
Project.unit<0>.dataChannel<4>=fifo_mem_pats din<4>
Project.unit<0>.dataChannel<5>=fifo_mem_pats din<3>
Project.unit<0>.dataChannel<6>=fifo_mem_pats din<2>
Project.unit<0>.dataChannel<7>=fifo_mem_pats din<1>
Project.unit<0>.dataChannel<8>=fifo_mem_pats din<0>
Project.unit<0>.dataChannel<9>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<7>
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=25
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=fifo_mem_pats wr_en
Project.unit<0>.triggerChannel<1><0>=fifo_mem_pats din<7>
Project.unit<0>.triggerChannel<1><1>=fifo_mem_pats din<6>
Project.unit<0>.triggerChannel<1><2>=fifo_mem_pats din<5>
Project.unit<0>.triggerChannel<1><3>=fifo_mem_pats din<4>
Project.unit<0>.triggerChannel<1><4>=fifo_mem_pats din<3>
Project.unit<0>.triggerChannel<1><5>=fifo_mem_pats din<2>
Project.unit<0>.triggerChannel<1><6>=fifo_mem_pats din<1>
Project.unit<0>.triggerChannel<1><7>=fifo_mem_pats din<0>
Project.unit<0>.triggerChannel<2><0>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<7>
Project.unit<0>.triggerChannel<2><1>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<6>
Project.unit<0>.triggerChannel<2><2>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<5>
Project.unit<0>.triggerChannel<2><3>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<4>
Project.unit<0>.triggerChannel<2><4>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<3>
Project.unit<0>.triggerChannel<2><5>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<2>
Project.unit<0>.triggerChannel<2><6>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<1>
Project.unit<0>.triggerChannel<2><7>=fifo_mem_pats U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/dout_i<0>
Project.unit<0>.triggerChannel<3><0>=fifo_mem_pats rd_en
Project.unit<0>.triggerChannel<4><0>=ROImager_inst/fsm_stat_i<5>
Project.unit<0>.triggerChannel<4><1>=ROImager_inst/fsm_stat_i<4>
Project.unit<0>.triggerChannel<4><2>=ROImager_inst/fsm_stat_i<3>
Project.unit<0>.triggerChannel<4><3>=ROImager_inst/fsm_stat_i<2>
Project.unit<0>.triggerChannel<4><4>=ROImager_inst/fsm_stat_i<1>
Project.unit<0>.triggerChannel<4><5>=ROImager_inst/fsm_stat_i<1>
Project.unit<0>.triggerChannel<5><0>=flag_2frames
Project.unit<0>.triggerChannel<6><0>=wire10 ep_dataout<0>
Project.unit<0>.triggerChannel<7><0>=ROImager_inst/FSMIND1_i
Project.unit<0>.triggerChannel<8><0>=ROImager_inst/FSMIND0ACK_i
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCount<7>=1
Project.unit<0>.triggerMatchCount<8>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchCountWidth<7><0>=0
Project.unit<0>.triggerMatchCountWidth<8><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerMatchType<7><0>=1
Project.unit<0>.triggerMatchType<8><0>=1
Project.unit<0>.triggerPortCount=7
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortIsData<7>=true
Project.unit<0>.triggerPortIsData<8>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerPortWidth<1>=8
Project.unit<0>.triggerPortWidth<2>=8
Project.unit<0>.triggerPortWidth<3>=1
Project.unit<0>.triggerPortWidth<4>=5
Project.unit<0>.triggerPortWidth<5>=1
Project.unit<0>.triggerPortWidth<6>=1
Project.unit<0>.triggerPortWidth<7>=1
Project.unit<0>.triggerPortWidth<8>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
